### PR TITLE
Simple FSPL error model

### PR DESCRIPTION
**Pull request by codyauch**
Added a super simple error model based on free space path loss

### CODE REVIEW

**Review by jjanzenn — APPROVED** [review]
lgtm

**Review by jjanzenn — CHANGES_REQUESTED** [review]
Could we add the error to the returned object from get_stats?

**Comment by codyauch** [comment]
I added the error rate to the stats object, also modified how the FSPL was being calculated. I wrapped the FSPL function in a get_error_rate function in case we want to modify the error calculation in the future.

**Review by jjanzenn — APPROVED** [review]
Looks great, thanks!

**Review by lysackm — APPROVED** [review]

**Pull request merged**
